version: '3.8'

services:
  # Neo4j Database Service
  neo4j:
    image: neo4j:5.15-community
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
    networks:
      - app-network

  # Ollama Service (not exposed to host to avoid conflicts)
  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

  # Streamlit Frontend Service
  frontend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen3:0.6b
      - PYTHONPATH=/workspaces/rrzz-rozbic-rzeczy-zrobione
    volumes:
      - .:/workspaces/rrzz-rozbic-rzeczy-zrobione
    working_dir: /workspaces/rrzz-rozbic-rzeczy-zrobione
    depends_on:
      - neo4j
      - ollama
    command: >
      sh -c "./scripts/pull_model.sh && streamlit run src/frontend/app.py --server.port 8501 --server.address 0.0.0.0"
    networks:
      - app-network

volumes:
  neo4j_data:
  ollama_data:

networks:
  app-network:
    driver: bridge 