version: '3.8'

services:
  # Neo4j Database Service
  neo4j:
    image: neo4j:5.15-community
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
    networks:
      - app-network

  # Ollama Service (not exposed to host to avoid conflicts)
  ollama:
    image: ollama/ollama
    profiles:
      - ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

volumes:
  neo4j_data:
  ollama_data:

networks:
  app-network:
    driver: bridge